### ISSUE TITLE
Maybe wrong implement of Kadmlia?

### ISSUE THREAD

**Issue by mengzhuo** [chewxy/nanjingtaxi#1]
According to http://en.wikipedia.org/wiki/Kademlia
The K-Bucket should be found by the distance.
However 
https://github.com/chewxy/nanjingtaxi/blob/master/kademlia/node.go#L67
tells me that the K-Bucket ID based on the first bits

**Comment by chewxy** [comment]
I'll look into it. Thanks for the heads up

**Comment by chewxy** [comment]
Closed with fix #2 by @mengzhuo
